spring:
  application:
    name: poklad
  datasource:
    url: jdbc:postgresql://localhost:5432/data2
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  thymeleaf:
    check-template-location: false
jwt:
  secret: ${SECRET_JAVA}
  expiration: 3600000
server:
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: classpath:keys/server.jks
    key-store-password: ${SECRET_KEYS}
    key-alias: server